Controllers/TintucController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace websitehoa.Controllers
{
    public class TintucController : Controller
    {
        public IActionResult Tintuc()
        {
            return View();
        }
        public IActionResult Tintucmot()
        {
            return View();
        }
        public IActionResult Tintuchai()
        {
            return View();
        }
        public IActionResult Tintucba()
        {
            return View();
        }
        public IActionResult Tintucbon()
        {
            return View();
        }
        public IActionResult Tintucnam()
        {
            return View();
        }
        public IActionResult Tintucsau()
        {
            return View();
        }
        public IActionResult Tintucbay()
        {
            return View();
        }
        public IActionResult Tintuctam()
        {
            return View();
        }
        public IActionResult noibatmot()
        {
            return View();
        }
        public IActionResult noibathai()
        {
            return View();
        }
        public IActionResult noibatba()
        {
            return View();
        }
        public IActionResult noibatbon()
        {
            return View();
        }
    }
}

Views/Tintuc/Tintucba.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="~/Content/scripts/zoomsl.min.js"></script>

<div class="ship-header">
    <strong>Giao sách tận nơi các Quận, Huyện tại Bình Dương</strong>
    <p><strong>Chuyên viên tư vấn :</strong><span>0123 456 789</span> - <span>0123 456 789</span><strong>(Tư vấn qua Zalo, FaceBook)</strong></p>
</div>
<div class="all-infoshop">
    <div class="row">
        <!---->

        <div class="col-md-9">

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background-color:#fff;margin-left:12px;">
                    <li class="breadcrumb-item"><a href="/" style="color:green;">Trang chủ</a></li>
                    <li class="breadcrumb-item active" aria-current="page" style="color:#ff5622;font-weight:700;">Thông tin</li> <!---->
                </ol>
            </nav>

            <main aria-labelledby="title">
               
                <!--<h2 id="title">@ViewBag.Title.</h2> --> 

                <div class="aboutshop">
                    <h4 style="margin-top:5px;">Chính Sách Quyền Riêng Tư</h4>
                    <div class="alltintuc">
                        <p>Chính Sách Quyền Riêng Tư. Để truy cập và sử dụng một số dịch vụ tại SachDTS, khách hàng có thể sẽ được yêu cầu đăng ký với chúng tôi thông tin cá nhân (Email, Họ tên, Số ĐT liên lạc…). Mọi thông tin khai báo phải đảm bảo tính chính xác và hợp pháp. Chúng tôi không chịu mọi trách nhiệm liên quan đến pháp luật của thông tin khai báo.</p>
                        <div>
                            <center>
                                <img class="img-responsive" src="~/Content/images/anhtintuc3.jpg" width="85%" />
                            </center>
                        </div>
                        <br />
                        <p>Dữ liệu cá nhân của khách hàng sẽ được lưu trữ cho đến khi có yêu cầu hủy bỏ hoặc khách hàng đăng nhập và thực hiện hủy bỏ.</p>
                        <h5>Cam kết bảo mật thông tin cá nhân khách hàng – Chính Sách Quyền Riêng Tư</h5>
                        <p>Chúng tôi cam kết không sử dụng, không chuyển giao, cung cấp hay tiết lộ cho bên thứ 3 nào về thông tin cá nhân của khách hàng khi không có sự cho phép đồng ý từ khách hàng đó.</p>
                        <p>Trong trường hợp máy chủ lưu trữ thông tin bị hacker tấn công dẫn đến mất mát dữ liệu cá nhân khách hàng, chúng tôi sẽ có trách nhiệm thông báo vụ việc cho cơ quan chức năng điều tra xử lý kịp thời và thông báo cho cá nhân được biết qua email hoặc số điện thoại.</p>
                    </div>
                </div>
            </main>
        </div>
        <!---->
        <div class="col-md-3">
            <!--tin tức nổi bật-->
            <div class="standout-block">
                <center>
                    <h5 style="margin-top:4px;">BÀI VIẾT NỔI BẬT</h5>
                    <hr />
                </center>
                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post1.png" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibatmot", "Tintuc")" style="color:black;">Sách nào sẽ thống trị làng sách trong năm 2025?</a></h6>
                        </div>
                    </div>
                </div>

                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post2.jpg" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibathai", "Tintuc")" style="color:black;">Sách kỹ năng sống – Hỗ trợ bạn trong những lúc cần thiết</a></h6>
                        </div>
                    </div>
                </div>

                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post3.jpg" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibatba", "Tintuc")" style="color:black;">Điểm danh các xu hướng cắm sách nổi bật năm 2025</a></h6>
                        </div>
                    </div>
                </div>

                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post2.jpg" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibatbon", "Tintuc")" style="color:black;">Cập nhật những mẫu sách đang được sao Việt ưa chuộng</a></h6>
                        </div>
                    </div>
                </div>
            </div>
            <!--end-->
    </div>
</div>





<div class="infoshop">
    <div class="row">
        <div class="sever-shop col-md-4">
            <div class="info1">
                <div class="row">
                    <div class="imgsever col-md-3">
                        <img src="~/Content/uploads/in1.png" class="img-fluid" />
                    </div>
                    <div class="col-md-9">
                        <h5>Giao hàng cực nhanh</h5>
                        <p>Miễn phí với đơn hàng trị giá trên 800.000đ</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="sever-shop col-md-4">
            <div class="info1">
                <div class="row">
                    <div class="imgsever col-md-3">
                        <img src="~/Content/uploads/info2.png" class="img-fluid" />
                    </div>
                    <div class="col-md-9">
                        <h5>Mua hàng siêu tiết kiệm</h5>
                        <p>Rẻ hơn từ 10% – 30% so với giá thị trường</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="sever-shop col-md-4">
            <div class="info1">
                <div class="row">
                    <div class="imgsever col-md-3">
                        <img src="~/Content/uploads/info3.png" class="img-fluid" />
                    </div>
                    <div class="col-md-9">
                        <h5>Sản phẩm chính hãng 100%</h5>
                        <p>Sản phẩm được nhập khẩu chính hãng</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<style>
    .list-group-item {
        transition: background-color 0.3s, color 0.3s;
    }

        .list-group-item:hover {
            background-color: green;
            color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

    .danhmuc {
        margin-top: 10px;
        padding: 12px 12px;
    }

        .danhmuc a {
            color: green;
        }

    .standout-block {
        padding: 0 17px;
    }

    .all-noibat {
        margin-top: 15px;
    }

        .all-noibat h6 {
            font-weight: 400;
        }

        .all-noibat img {
            width: 100%;
            height: auto;
            margin-top: 11px;
        }

    .ship-header {
        padding: 26px 0;
        text-align: center;
    }

        .ship-header span {
            font-weight: 700;
            color: red;
            margin: 0 6px;
        }

    .aboutshop {
        padding: 12px 28px;
    }

    .infoshop {
        padding: 20px 20px;
        margin-top: 20px;
    }

    .info1 img {
        width: 100%;
        height: auto;
    }

    .info1 h5 {
        color: green;
    }

    .bannerhoa {
        border-radius: 5px;
        height: 100px;
        text-align: center;
        display: flex;
        justify-content: center;
        align-items: center;
    }

        .bannerhoa > div {
            font-size: 20px;
        }

</style>

Views/Tintuc/Tintucbay.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="~/Content/scripts/zoomsl.min.js"></script>

<div class="ship-header">
    <strong>Giao sách tận nơi các Quận, Huyện tại Bình Dương</strong>
    <p><strong>Chuyên viên tư vấn :</strong><span>0123 456 789</span> - <span>0123 456 789</span><strong>(Tư vấn qua Zalo, FaceBook)</strong></p>
</div>
<div class="all-infoshop">
    <div class="row">
        <!---->

        <div class="col-md-9">

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb" style="background-color:#fff;margin-left:12px;">
                    <li class="breadcrumb-item"><a href="/" style="color:green;">Trang chủ</a></li>
                    <li class="breadcrumb-item active" aria-current="page" style="color:#ff5622;font-weight:700;">Thông tin</li> <!---->
                </ol>
            </nav>

            <main aria-labelledby="title">
               
                <!--<h2 id="title">@ViewBag.Title.</h2> --> 

                <div class="aboutbook">
                    <strong> Sách sinh nhật là biểu tượng của sự tôn trọng và lời chúc mừng đến đối phương. Bởi thế, sách sinh nhật đóng vai trò vô cùng quan trọng gắn kết tình cảm với nhau. Tuy nhiên, không phải ai cũng biết cách chọn sách sinh nhật và những điều cần lưu ý khi lựa sách. Hãy cùng [Tên Nhà Sách/Trang Web Của Bạn] tìm hiểu trong bài viết nhé. </strong>
                    <h4 style="margin-top:5px;">Vì sao nên tặng sách sinh nhật?</h4>
                    <p>Mỗi cuốn sách với thể loại, nội dung khác nhau sẽ gắn với thông điệp gửi tới người nhận. Vì thế, tặng sách nhân ngày sinh nhật trở nên phổ biến. Tùy vào đối tượng được nhận, sách sinh nhật sẽ khác nhau. </p>
                    <p>Tặng sách sinh nhật vừa mang đến niềm vui cho người tặng lẫn người nhận. Những trang sách chứa đựng tri thức, câu chuyện ý nghĩa mang đến cảm giác thư thái và mở mang. Hơn nữa, sách rất phù hợp để tặng những người yêu thích đọc sách và khám phá. Khi tặng những cuốn sách giống như bạn đang tôn vinh trí tuệ và thế giới nội tâm của người đó. </p>
                    <div>
                        <center>
                            <img class="img-responsive" src="https://via.placeholder.com/300/D8BFD8/000000?Text=Stack+of+Birthday+Books" width="85%" />
                        </center>
                    </div>
                    <h4 style="margin-top:5px;">Nên mua sách sinh nhật nào?</h4>
                    <h6 style="margin-top:3px;">Tiểu thuyết</h6>
                    <p>Tiểu thuyết là thể loại sách được lựa chọn để tặng cho sinh nhật phổ biến nhất. Tiểu thuyết được mệnh danh là "nữ hoàng" của thế giới văn chương. Với những câu chuyện hấp dẫn, tiểu thuyết từ lâu đã trở thành sách sinh nhật dành tặng người yêu văn học, hay những người bạn trân quý những phút giây đắm mình trong trang sách. </p>
                    <h6 style="margin-top:3px;">Sách Phát Triển Bản Thân</h6>
                    <p>Sách phát triển bản thân cũng là một thể loại được ưa chuộng để tặng trong ngày sinh nhật. Nội dung sách mang đến những bài học, động lực thể hiện được sự quan tâm của bạn dành cho sự phát triển của đối phương. Ngoài ra, sách phát triển bản thân cũng là biểu tượng cho sự khuyến khích, mong muốn người nhận ngày càng hoàn thiện. </p>
                    <p>Sách sinh nhật từ những tựa sách phát triển bản thân biểu thị rằng bạn thật sự rất coi trọng sự tiến bộ của người đó. Bạn cũng đang khẳng định niềm tin vào tiềm năng của họ. </p>
                    <p>Ngoài ra, còn rất nhiều thể loại sách sinh nhật bạn có thể tặng trong ngày sinh nhật như sách trinh thám, sách khoa học, sách nghệ thuật... Mỗi thể loại đều có ý nghĩa riêng, vì vậy hãy lựa chọn sách thật sự phù hợp với sở thích và thông điệp bạn muốn gửi đến đối phương nhé.</p>
                    <h4 style="margin-top:5px;">Các mẫu "bộ sưu tập" sách sinh nhật năm 2024</h4>
                    <h6 style="margin-top:3px;">Bộ sách sinh nhật theo chủ đề</h6>
                    <p>Bộ sách sinh nhật theo chủ đề là tập hợp những cuốn sách nhỏ được lựa chọn, kết hợp với những món quà tặng kèm ý nghĩa. Do đó, món quà sách sinh nhật sẽ càng được nổi bật và vô cùng tinh tế. Bộ sách có thể được sắp xếp theo sở thích, theo thể loại hoặc theo tác giả phù hợp cho mọi đối tượng. Bộ sách sinh nhật bạn có thể tìm thấy ở nhiều nhà sách nhưng nếu bạn muốn có bộ sách độc đáo theo ý mình thì nên liên hệ để được tư vấn và thiết kế riêng. </p>
                    <div>
                        <center>
                            <img class="img-responsive" src="https://via.placeholder.com/300/E0FFFF/000000?Text=Birthday+Book+Set" width="75%" />
                        </center>
                    </div>
                    <h6 style="margin-top:3px;">Giỏ sách sinh nhật</h6>
                    <p>Giỏ sách sinh nhật ngày càng được yêu thích bởi sự trang trọng và tiện lợi. Sách sinh nhật được lựa chọn cẩn thận và sắp xếp hợp lý cùng với những phụ kiện xinh xắn để giỏ sách luôn đẹp mắt và hiện đại. Giỏ sách rất phù hợp để tặng cho người thân, bạn bè hoặc đồng nghiệp. </p>
                    <p>Hộp sách sinh nhật cũng là một trong những mẫu quà tặng sách được yêu thích lựa chọn. Hộp sách với nhiều cách thiết kế và màu sắc khác nhau luôn thu hút được người nhận. Tuy nhiên, muốn hộp sách đẹp và đúng ý cần phải lựa chọn nhà sách uy tín và có dịch vụ gói quà chuyên nghiệp.</p>
                    <h6 style="margin-top:3px;">Chọn sách mới và chất lượng</h6>
                    <p>Khi chọn sách sinh nhật hay bất kì cho dịp nào thì điều quan trọng nhất là lựa chọn sách phải mới và có chất lượng tốt. Bạn cần chọn những cuốn sách còn nguyên vẹn, không bị rách, in ấn rõ ràng, như vậy món quà mới đẹp và ý nghĩa. Ngoài ra, khi chọn sách bạn cần chú ý đến nội dung và thể loại phù hợp với người nhận. Tốt nhất, bạn nên lựa chọn những cuốn sách mà người nhận có thể yêu thích và đọc được lâu dài. </p>
                    <h6 style="margin-top:3px;">Lựa chọn nhà sách uy tín</h6>
                    <p>Để có được món quà sách sinh nhật thật đặc biệt thì điều quan trọng không thể thiếu chính là lựa chọn nhà sách uy tín. Những nhà sách uy tín, chuyên nghiệp mới có thể mang đến những cuốn sách chất lượng và những gợi ý phù hợp nhất với thông điệp bạn muốn gửi gắm.</p>
                </div>
            </main>
        </div>
        <!---->
        <div class="col-md-3">
            <!--tin tức nổi bật-->
            <div class="standout-block">
                <center>
                    <h5 style="margin-top:4px;">BÀI VIẾT NỔI BẬT</h5>
                    <hr />
                </center>
                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post1.png" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibatmot", "Tintuc")" style="color:black;">Sách nào sẽ thống trị làng sách trong năm 2025?</a></h6>
                        </div>
                    </div>
                </div>

                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post2.jpg" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibathai", "Tintuc")" style="color:black;">Sách kỹ năng sống – Hỗ trợ bạn trong những lúc cần thiết</a></h6>
                        </div>
                    </div>
                </div>

                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post3.jpg" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibatba", "Tintuc")" style="color:black;">Điểm danh các xu hướng cắm sách nổi bật năm 2025</a></h6>
                        </div>
                    </div>
                </div>

                <div class="all-noibat">
                    <div class="row">
                        <div class="col-sm-3">
                            <img src="~/Content/uploads/post2.jpg" class="img-fluid" />
                        </div>
                        <div class="col-sm-9">
                            <h6> <a href="@Url.Action("noibatbon", "Tintuc")" style="color:black;">Cập nhật những mẫu sách đang được sao Việt ưa chuộng</a></h6>
                        </div>
                    </div>
                </div>
            </div>
            <!--end-->
            <div class="danhmuc">
                <div class="list-group" style="border-radius:0px;margin-top:7px;">
                    <a href="#" style="color:red;text-align:center;" class="list-group-item list-group-item-action">Danh mục sản phẩm </a>
                    <a class="list-group-item list-group-item-action" asp-controller="SanPham" asp-action="hoacamon">Sách cảm ơn</a>
                    <a class="list-group-item list-group-item-action" asp-controller="SanPham" asp-action="hoasinhnhat">Sách sinh nhật</a>
                    <a class="list-group-item list-group-item-action" asp-controller="SanPham" asp-action="hoasukien">Sách sự kiện</a>
                    <a class="list-group-item list-group-item-action" asp-controller="SanPham" asp-action="hoaquatang">Sách quà tặng</a>
                    <a class="list-group-item list-group-item-action" asp-controller="SanPham" asp-action="hoatonghop">Sách tổng hợp</a>
                    <a class="list-group-item list-group-item-action" asp-controller="SanPham" asp-action="hoanhagiao">Sách ngày nhà giáo</a>
                </div>
            </div>
        </div>
        <!---->
    </div>
</div>





<div class="infoshop">
    <div class="row">
        <div class="sever-shop col-md-4">
            <div class="info1">
                <div class="row">
                    <div class="imgsever col-md-3">
                        <img src="~/Content/uploads/in1.png" class="img-fluid" />
                    </div>
                    <div class="col-md-9">
                        <h5>Giao hàng cực nhanh</h5>
                        <p>Miễn phí với đơn hàng trị giá trên 800.000đ</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="sever-shop col-md-4">
            <div class="info1">
                <div class="row">
                    <div class="imgsever col-md-3">
                        <img src="~/Content/uploads/info2.png" class="img-fluid" />
                    </div>
                    <div class="col-md-9">
                        <h5>Mua hàng siêu tiết kiệm</h5>
                        <p>Rẻ hơn từ 10% – 30% so với giá thị trường</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="sever-shop col-md-4">
            <div class="info1">
                <div class="row">
                    <div class="imgsever col-md-3">
                        <img src="~/Content/uploads/info3.png" class="img-fluid" />
                    </div>
                    <div class="col-md-9">
                        <h5>Sản phẩm chính hãng 100%</h5>
                        <p>Sản phẩm được nhập khẩu chính hãng</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<style>
    .list-group-item {
        transition: background-color 0.3s, color 0.3s;
    }

        .list-group-item:hover {
            background-color: green;
            color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

    .danhmuc {
        margin-top: 10px;
        padding: 12px 12px;
    }

        .danhmuc a {
            color: green;
        }

    .standout-block {
        padding: 0 17px;
    }

    .all-noibat {
        margin-top: 15px;
    }

        .all-noibat h6 {
            font-weight: 400;
        }

        .all-noibat img {
            width: 100%;
            height: auto;
            margin-top: 11px;
        }

    .ship-header {
        padding: 26px 0;
        text-align: center;
    }

        .ship-header span {
            font-weight: 700;
            color: red;
            margin: 0 6px;
        }

    .aboutshop {
        padding: 12px 28px;
    }

    .infoshop {
        padding: 20px 20px;
        margin-top: 20px;
    }

    .info1 img {
        width: 100%;
        height: auto;
    }

    .info1 h5 {
        color: green;
    }

    .bannerhoa {
        border-radius: 5px;
        height: 100px;
        text-align: center;
        display: flex;
        justify-content: center;
        align-items: center;
    }

        .bannerhoa > div {
            font-size: 20px;
        }

</style>